services:
  # Pwn
  injection:
    build: ./pwn/injection/src
    ports:
      - "9000:9000"
    restart: on-failure

  overflow1:
    build: ./pwn/overflow1/src
    ports:
      - "9001:9001"
    restart: on-failure

  overflow2:
    build: ./pwn/overflow2/src
    ports:
      - "9002:9002"
    restart: on-failure

  # Web
  sql_injection:
    build: ./web/sql_injection/src
    ports:
      - "8001:8001"
    restart: on-failure

  hidden:
    build: ./web/hidden/src
    ports:
      - "8002:8002"
    restart: on-failure

  flask_admin:
    build: ./web/flask_admin/src
    ports:
      - "8003:8003"
    restart: on-failure
